"""created

Revision ID: bf1c36262a7d
Revises: 416128cb613f
Create Date: 2024-07-01 08:34:41.722097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1c36262a7d'
down_revision = '416128cb613f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
